// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11.2.2025, 11:31:24
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/plugins/**/*.{js,ts,mjs}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/composables/**/*.{js,ts,mjs}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/utils/**/*.{js,ts,mjs}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/app.config.{js,ts,mjs}","/Users/z0046t6p/Repositories/chat/DeepSeek-Desktop/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;