
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'ChatInputBar': typeof import("../components/ChatInputBar.vue")['default']
    'ChatMessages': typeof import("../components/ChatMessages.vue")['default']
    'ProseA': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
    'ProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'ProseCode': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
    'ProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'ProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'ProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'ProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'ProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'ProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'ProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'ProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'ProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'ProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'ProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'ProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'ProsePre': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue")['default']
    'ProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'ProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'ProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'ProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'ProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'ProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'ProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'ProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'ProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Badge': typeof import("../components/ui/badge/index")['Badge']
    'Breadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'BreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'BreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'BreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'BreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'BreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'BreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Card': typeof import("../components/ui/card/index")['Card']
    'CardContent': typeof import("../components/ui/card/index")['CardContent']
    'CardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'CardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'CardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'CardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'Drawer': typeof import("../components/ui/drawer/index")['Drawer']
    'DrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'DrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'DrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'DrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'DrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'DrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'DrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'DrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'DrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'DropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'DropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'DropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'DropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'DropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'DropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'DropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'DropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'DropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'DropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'DropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'DropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'DropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'DropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'DropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'Input': typeof import("../components/ui/input/index")['Input']
    'Label': typeof import("../components/ui/label/index")['Label']
    'Select': typeof import("../components/ui/select/index")['Select']
    'SelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'SelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'SelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'SelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'SelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'SelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'SelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'SelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'SelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'SelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'Separator': typeof import("../components/ui/separator/index")['Separator']
    'Sheet': typeof import("../components/ui/sheet/index")['Sheet']
    'SheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'SheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'SheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'SheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'SheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'SheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'SheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'Sidebar': typeof import("../components/ui/sidebar/index")['Sidebar']
    'SidebarContent': typeof import("../components/ui/sidebar/index")['SidebarContent']
    'SidebarFooter': typeof import("../components/ui/sidebar/index")['SidebarFooter']
    'SidebarGroup': typeof import("../components/ui/sidebar/index")['SidebarGroup']
    'SidebarGroupAction': typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
    'SidebarGroupContent': typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
    'SidebarGroupLabel': typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
    'SidebarHeader': typeof import("../components/ui/sidebar/index")['SidebarHeader']
    'SidebarInput': typeof import("../components/ui/sidebar/index")['SidebarInput']
    'SidebarInset': typeof import("../components/ui/sidebar/index")['SidebarInset']
    'SidebarMenu': typeof import("../components/ui/sidebar/index")['SidebarMenu']
    'SidebarMenuAction': typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
    'SidebarMenuBadge': typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
    'SidebarMenuButton': typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
    'SidebarMenuItem': typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
    'SidebarMenuSkeleton': typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
    'SidebarMenuSub': typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
    'SidebarMenuSubButton': typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
    'SidebarMenuSubItem': typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
    'SidebarProvider': typeof import("../components/ui/sidebar/index")['SidebarProvider']
    'SidebarRail': typeof import("../components/ui/sidebar/index")['SidebarRail']
    'SidebarSeparator': typeof import("../components/ui/sidebar/index")['SidebarSeparator']
    'SidebarTrigger': typeof import("../components/ui/sidebar/index")['SidebarTrigger']
    'Skeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'Textarea': typeof import("../components/ui/textarea/index")['Textarea']
    'Toast': typeof import("../components/ui/toast/index")['Toast']
    'ToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'ToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'ToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'Toaster': typeof import("../components/ui/toast/index")['Toaster']
    'ToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'ToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'ToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'Tooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'TooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'TooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'TooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'MDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'MDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'MDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyChatInputBar': typeof import("../components/ChatInputBar.vue")['default']
    'LazyChatMessages': typeof import("../components/ChatMessages.vue")['default']
    'LazyProseA': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
    'LazyProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'LazyProseCode': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
    'LazyProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'LazyProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'LazyProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'LazyProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'LazyProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'LazyProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'LazyProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'LazyProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'LazyProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'LazyProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'LazyProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'LazyProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'LazyProsePre': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue")['default']
    'LazyProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'LazyProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'LazyProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'LazyProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'LazyProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'LazyProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'LazyProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'LazyProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'LazyProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyBadge': typeof import("../components/ui/badge/index")['Badge']
    'LazyBreadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'LazyBreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'LazyBreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'LazyBreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'LazyBreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'LazyBreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'LazyBreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazyCard': typeof import("../components/ui/card/index")['Card']
    'LazyCardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyDrawer': typeof import("../components/ui/drawer/index")['Drawer']
    'LazyDrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'LazyDrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'LazyDrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'LazyDrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'LazyDrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'LazyDrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'LazyDrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'LazyDrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'LazyDrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'LazyDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyLabel': typeof import("../components/ui/label/index")['Label']
    'LazySelect': typeof import("../components/ui/select/index")['Select']
    'LazySelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'LazySelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'LazySelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'LazySelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'LazySelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'LazySelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'LazySelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'LazySelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'LazySelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'LazySelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'LazySeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazySheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazySheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazySheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazySheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazySheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazySheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazySheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazySheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazySidebar': typeof import("../components/ui/sidebar/index")['Sidebar']
    'LazySidebarContent': typeof import("../components/ui/sidebar/index")['SidebarContent']
    'LazySidebarFooter': typeof import("../components/ui/sidebar/index")['SidebarFooter']
    'LazySidebarGroup': typeof import("../components/ui/sidebar/index")['SidebarGroup']
    'LazySidebarGroupAction': typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
    'LazySidebarGroupContent': typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
    'LazySidebarGroupLabel': typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
    'LazySidebarHeader': typeof import("../components/ui/sidebar/index")['SidebarHeader']
    'LazySidebarInput': typeof import("../components/ui/sidebar/index")['SidebarInput']
    'LazySidebarInset': typeof import("../components/ui/sidebar/index")['SidebarInset']
    'LazySidebarMenu': typeof import("../components/ui/sidebar/index")['SidebarMenu']
    'LazySidebarMenuAction': typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
    'LazySidebarMenuBadge': typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
    'LazySidebarMenuButton': typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
    'LazySidebarMenuItem': typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
    'LazySidebarMenuSkeleton': typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
    'LazySidebarMenuSub': typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
    'LazySidebarMenuSubButton': typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
    'LazySidebarMenuSubItem': typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
    'LazySidebarProvider': typeof import("../components/ui/sidebar/index")['SidebarProvider']
    'LazySidebarRail': typeof import("../components/ui/sidebar/index")['SidebarRail']
    'LazySidebarSeparator': typeof import("../components/ui/sidebar/index")['SidebarSeparator']
    'LazySidebarTrigger': typeof import("../components/ui/sidebar/index")['SidebarTrigger']
    'LazySkeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'LazyTextarea': typeof import("../components/ui/textarea/index")['Textarea']
    'LazyToast': typeof import("../components/ui/toast/index")['Toast']
    'LazyToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'LazyToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'LazyToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'LazyToaster': typeof import("../components/ui/toast/index")['Toaster']
    'LazyToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'LazyToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'LazyToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'LazyTooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'LazyTooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'LazyTooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'LazyTooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'LazyMDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'LazyMDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'LazyMDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ChatInputBar: typeof import("../components/ChatInputBar.vue")['default']
export const ChatMessages: typeof import("../components/ChatMessages.vue")['default']
export const ProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProsePre: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Badge: typeof import("../components/ui/badge/index")['Badge']
export const Breadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const BreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const BreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const BreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const BreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const BreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const BreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Card: typeof import("../components/ui/card/index")['Card']
export const CardContent: typeof import("../components/ui/card/index")['CardContent']
export const CardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const CardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const CardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const Drawer: typeof import("../components/ui/drawer/index")['Drawer']
export const DrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const DrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const DrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const DrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const DrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const DrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const DrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const DrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const DrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const Input: typeof import("../components/ui/input/index")['Input']
export const Label: typeof import("../components/ui/label/index")['Label']
export const Select: typeof import("../components/ui/select/index")['Select']
export const SelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const SelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const SelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const SelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const SelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const SelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const Separator: typeof import("../components/ui/separator/index")['Separator']
export const Sheet: typeof import("../components/ui/sheet/index")['Sheet']
export const SheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const SheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const SheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const SheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const Sidebar: typeof import("../components/ui/sidebar/index")['Sidebar']
export const SidebarContent: typeof import("../components/ui/sidebar/index")['SidebarContent']
export const SidebarFooter: typeof import("../components/ui/sidebar/index")['SidebarFooter']
export const SidebarGroup: typeof import("../components/ui/sidebar/index")['SidebarGroup']
export const SidebarGroupAction: typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
export const SidebarGroupContent: typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
export const SidebarGroupLabel: typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
export const SidebarHeader: typeof import("../components/ui/sidebar/index")['SidebarHeader']
export const SidebarInput: typeof import("../components/ui/sidebar/index")['SidebarInput']
export const SidebarInset: typeof import("../components/ui/sidebar/index")['SidebarInset']
export const SidebarMenu: typeof import("../components/ui/sidebar/index")['SidebarMenu']
export const SidebarMenuAction: typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
export const SidebarMenuBadge: typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
export const SidebarMenuButton: typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
export const SidebarMenuItem: typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
export const SidebarMenuSkeleton: typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
export const SidebarMenuSub: typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
export const SidebarMenuSubButton: typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
export const SidebarMenuSubItem: typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
export const SidebarProvider: typeof import("../components/ui/sidebar/index")['SidebarProvider']
export const SidebarRail: typeof import("../components/ui/sidebar/index")['SidebarRail']
export const SidebarSeparator: typeof import("../components/ui/sidebar/index")['SidebarSeparator']
export const SidebarTrigger: typeof import("../components/ui/sidebar/index")['SidebarTrigger']
export const Skeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const Textarea: typeof import("../components/ui/textarea/index")['Textarea']
export const Toast: typeof import("../components/ui/toast/index")['Toast']
export const ToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const ToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const ToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const Toaster: typeof import("../components/ui/toast/index")['Toaster']
export const ToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const ToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const ToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const Tooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const TooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const TooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyChatInputBar: typeof import("../components/ChatInputBar.vue")['default']
export const LazyChatMessages: typeof import("../components/ChatMessages.vue")['default']
export const LazyProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const LazyProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const LazyProseCode: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
export const LazyProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const LazyProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const LazyProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const LazyProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const LazyProsePre: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProsePre.vue")['default']
export const LazyProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const LazyProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyBadge: typeof import("../components/ui/badge/index")['Badge']
export const LazyBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const LazyBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const LazyBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const LazyBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const LazyBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const LazyBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const LazyBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazyCard: typeof import("../components/ui/card/index")['Card']
export const LazyCardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyDrawer: typeof import("../components/ui/drawer/index")['Drawer']
export const LazyDrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const LazyDrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const LazyDrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const LazyDrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const LazyDrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const LazyDrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const LazyDrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const LazyDrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const LazyDrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const LazyDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyLabel: typeof import("../components/ui/label/index")['Label']
export const LazySelect: typeof import("../components/ui/select/index")['Select']
export const LazySelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const LazySelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const LazySelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const LazySelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const LazySelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const LazySelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const LazySelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const LazySelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const LazySelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const LazySelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const LazySeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazySheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazySheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazySheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazySheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazySheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazySheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazySheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazySheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazySidebar: typeof import("../components/ui/sidebar/index")['Sidebar']
export const LazySidebarContent: typeof import("../components/ui/sidebar/index")['SidebarContent']
export const LazySidebarFooter: typeof import("../components/ui/sidebar/index")['SidebarFooter']
export const LazySidebarGroup: typeof import("../components/ui/sidebar/index")['SidebarGroup']
export const LazySidebarGroupAction: typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
export const LazySidebarGroupContent: typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
export const LazySidebarGroupLabel: typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
export const LazySidebarHeader: typeof import("../components/ui/sidebar/index")['SidebarHeader']
export const LazySidebarInput: typeof import("../components/ui/sidebar/index")['SidebarInput']
export const LazySidebarInset: typeof import("../components/ui/sidebar/index")['SidebarInset']
export const LazySidebarMenu: typeof import("../components/ui/sidebar/index")['SidebarMenu']
export const LazySidebarMenuAction: typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
export const LazySidebarMenuBadge: typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
export const LazySidebarMenuButton: typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
export const LazySidebarMenuItem: typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
export const LazySidebarMenuSkeleton: typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
export const LazySidebarMenuSub: typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
export const LazySidebarMenuSubButton: typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
export const LazySidebarMenuSubItem: typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
export const LazySidebarProvider: typeof import("../components/ui/sidebar/index")['SidebarProvider']
export const LazySidebarRail: typeof import("../components/ui/sidebar/index")['SidebarRail']
export const LazySidebarSeparator: typeof import("../components/ui/sidebar/index")['SidebarSeparator']
export const LazySidebarTrigger: typeof import("../components/ui/sidebar/index")['SidebarTrigger']
export const LazySkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const LazyTextarea: typeof import("../components/ui/textarea/index")['Textarea']
export const LazyToast: typeof import("../components/ui/toast/index")['Toast']
export const LazyToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const LazyToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const LazyToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const LazyToaster: typeof import("../components/ui/toast/index")['Toaster']
export const LazyToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const LazyToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const LazyToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const LazyTooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const LazyTooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const LazyTooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const LazyTooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const LazyMDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const LazyMDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const LazyMDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
